- doc/cortx-aws-k8s-installation.md
Signed-off-by: Gregory Touretsky <gregory.touretsky@gmail.com>
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/gregnsk/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md)
> typo fixed

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_dummy.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
https://jts.seagate.com/browse/UDX-6755
> UDX-6755 update release keys fix

- k8_cortx_cloud/solution_validation_scripts/solution-validation.sh
> fix incorrect SNS validation

- doc/cortx-aws-k8s-installation.md
Signed-off-by: Gregory Touretsky <gregory.touretsky@gmail.com>
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/gregnsk/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md)
> Updated the procedure for K8s 1.23

- doc/cortx-aws-k8s-installation.md
Signed-off-by: Gregory Touretsky <gregory.touretsky@gmail.com>
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/gregnsk/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md)
> updated git clone path

- k8_cortx_cloud/solution_dummy.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
> Adding missed solution.yaml impacted files

- k8_cortx_cloud/logs-cortx-cloud.sh
As per suggestion by @ujjwalpl & @cdeshmukh,
Logs collection script should be able to give the logs from a particular node only.
Added the node level filter.
> UDX-6756: Add node level filter to collect cortx-cloud logs script.

- k8_cortx_cloud/cortx-cloud-3rd-party-pkg/openldap/templates/openldap-statefulset.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-networkpolicy.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-podsecuritypolicy-baseline.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
This will solve what we can feasibly control as an external consumer of the third-party charts, but it should hit the majority of what we need for right now.
> Initial pass for zk/kafka/consul/openldap

- k8_cortx_cloud/generate-cvg-yaml.sh
> UDX-6925 -  generate cvg yaml option long names

- doc/cortx-aws-k8s-installation.md
Added a Note for Motr + Hare cluster in cortx level QSG ( section 3.5 )
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/JugalPatil/cortx-k8s/blob/QSG-update-Motr+Hare/doc/cortx-aws-k8s-installation.md)
> Update cortx-aws-k8s-installation.md for Motr + Hare cortx cluster

- doc/cortx-aws-k8s-installation.md
- k8_cortx_cloud/deploy-cortx-cloud.sh
I have pushed these changes to allow for configuration at run-time, but not hard coding them to the original minimal value of '1' that was requested in JIRA, as that will overload the Kafka system (based on our lower amount of resources provided to Kafka).
> UDX-7022 Kafka performance config updates

- k8_cortx_cloud/start-cortx-cloud.sh
- exit wait loop if an error is detected while a pod is restarting
> UDX-7058_start_script_hangs_if_pod_fails_to_restart

- k8_cortx_cloud/services/cortx-io-svc.yaml
> UDX-7074 - Updated cortx-io-svc with correct selector

- k8_cortx_cloud/cortx-cloud-3rd-party-pkg/templates/local-path-storage-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Ran successful CI build in Jenkins via http://eos-jenkins.colo.seagate.com/job/Cortx-Kubernetes/job/setup-cortx-cluster-solution-input/279/
> EOS-27545 update local path prov ghcr busybox

- k8_cortx_cloud/logs-cortx-cloud.sh
Sometimes the log output from a container is so large that capturing it
in a variable and printing it will cause bash to crash. Instead of
capturing, just redirect the log output directly to the destination
file. This does have a side-effect of creating an empty log file if a
pod/container has no logs, where previously it would skip the file if
the logs were empty.
Other fixes:
- Remove leading `./` from paths in the output tar file
- Fix some Shellcheck complaints
- Use long options for `tar` and `cortx_support_bundle` commands
(script self-documentation)
- Reduce some code duplication
> EOS-27575: Avoid capturing container logs as variables

- .github/workflows/alex_reviewdog.yml
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
> Added the Alex workflow

- README.md
-----
[View rendered README.md](https://github.com/osowski/cortx-k8s/blob/integration/README.md)
> Patch for README.md GitHub formatting

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Remove unneeded services: cortx-control-headless-svc and cortx-control-cluster-ip-svc.
https://jts.seagate.com/browse/EOS-28404
> Remove unneeded control services

- doc/cortx-aws-k8s-installation.md
null
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/walterlopatka/cortx-k8s/blob/integration/doc/cortx-aws-k8s-installation.md)
> Merge main into Integration

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-data-template.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-data-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
> EOS-27644 Test and qualify granular deployment-Data Pod only

- k8_cortx_cloud/deploy-cortx-cloud.sh
Signed-off-by: Walter Lopatka <wlopatka@gmail.com>
> EOS-28489 remove dup line in cortxha helm deploy 

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
> node ports for cortx-rgw container

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
> EOS-27648 Adding config updates for RGW and marking deleted items

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-hax-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Implements a new ClusterIP Service for HAX-enabled Data & Server Pods.
> EOS-27447 -  clusterip svc for hax

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-template.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
Based on discussion in EOS-28075 and updates in the `cortx-test` branch here, these changes should be all-encompassing for the cortx-client requirements:
- Adding cortx-client Helm deployments when specified in solution.yaml
- Updating ConfigMaps with appropriate cortx-client endpoints & metadata
- Updating deploy/undeploy scripts for additional elements being deployed/cleaned up.
> EOS-28075 - cortx-client Helm implementation updates

- k8_cortx_cloud/solution.yaml
> Bump default cort-all image tag

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
> CORTX-28890: removed hardcoded rgw inst from config template

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_cluster.tpl
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
This is the first phase of RGW integration for the "big bang" approach taken during Sprint 63. All the initial changes necessary to support IO through the RGW interface layer are included in this PR, along with enhancements that coincide with other recent changes (ie CORTX-27406 etc).
> CORTX- 28078 - RGW integration, phase 1

- README.md
-----
[View rendered README.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-29102_readme_aws_qsg_typo/README.md)
> CORTX-29102 - Fix AWS QSG URL typo

- README.md
- doc/cortx-minikube-k8s-installation.md
This document explains the procedure to deploy cortx k8s
using minikube.
Signed-off-by: Sayed Alfhad <fahadshah2411@gmail.com>
Signed-off-by: Rose Wambui <rose.wambui@seagate.com>
Signed-off-by: Rinku Kothiya <rinku.kothiya@seagate.com>
-----
[View rendered doc/cortx-minikube-k8s-installation.md](https://github.com/alfhad/cortx-k8s/blob/issue-89/doc/cortx-minikube-k8s-installation.md)
> Issue-89: Doc for minikube deployment created.

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
> CORTX-28904: new keys and service endpoints added for cortx-rgw

- .alexrc
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
**Problem Statement:**
Alex scan generate false positive
**Solution:**
We have added some allowable list to ignore the false positives.
> CORTX-28870: Adding the allowable list for Alex scan 

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
> CORTX-28904:changed rgw external ports to 80 & 443

- k8_cortx_cloud/solution.yaml
> Update container images to latest released

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
> CORTX-29228: removed sleep infinity from cortx-rgw conatiner

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>
> CORTX-29029: support for multiple m0d instances with group_size

- doc/cortx-minikube-k8s-installation.md
Signed-off-by: wb-droid <bo.b.wei@seagate.com>
-----
[View rendered doc/cortx-minikube-k8s-installation.md](https://github.com/wb-droid/cortx-k8s/blob/minikube/doc/cortx-minikube-k8s-installation.md)
> Test Cortx k8s single node setup with minikube.

- .github/workflows/lint.yaml
- k8_cortx_cloud/shutdown-cortx-cloud.sh
Fix all shellcheck errors, warnings and notes. Re-enable GitHub lint action for the script.
> CORTX-29202: Fix shellcheck issues in shutdown-cortx-cloud.sh

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
> CORTX:29228:removed sleep infinity from csm & hax

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
> CORTX-29503 - removed sleep infinity from rgw,csm & hax

- .github/workflows/lint.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Remove `num_inst` from solution-check.yaml.
> CORTX-29179: Remove common.s3.num_inst from solution.yaml validation

- .github/workflows/lint.yaml
> Lint solution.example.yaml

- k8_cortx_cloud/deploy-cortx-cloud.sh
Adding a newline to the end of deploy-cortx-cloud.sh to improve appearance.
> CORTX-29800: Add newline to final printf of deploy-cortx-cloud.sh

- k8_cortx_cloud/VERSION
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
The contents of the v0.2.1 release are in a v0.2 branch.  This PR brings these changes into main.
> Merge v0.2 branch into main

- k8_cortx_cloud/upgrade-cortx-cloud.sh
…ror/loopbackoff state
Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>
> CORTX-29809: Upgrade script should throw an error when invalid image passed.

- .github/workflows/lint.yaml
- k8_cortx_cloud/destroy-cortx-cloud.sh
Fix all shellcheck errors, warnings and notes. Re-enable GitHub lint action for the script.
- This change fixes an issue: CORTX-29537
Ran script to tear-down cluster.
> CORTX-29537: Fix shellcheck issues in destroy-cortx-cloud.sh

- README.md
Additional debugging instructions were added to the root README's troubleshooting section. 
- This change fixes an issue: # CORTX-30138
Manually verified through multiple debugging sessions.
-----
[View rendered README.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-30138_updated_troubleshooting_steps/README.md)
> CORTX-30138 - added InitContainer debug troubleshooting steps

- test/regression/cluster.py
- test/regression/cortx-k8s-tests.md
- test/regression/example_config.yaml
- test/regression/testlists/alltests.yaml
Update regtests for v0.2.0 solution.yaml updates
* use solution.example.yaml instead of solution.yaml
* add support for setting secrets in config file
* add support for setting nodeports in config file
(not related to v0.2.0)
* `./testrunner.py -c 594.yaml -t testlists/deploy_all.py`, where `594.yaml` is my local config with new changes
* Ran special manual tests to be sure that the nodeport solution.yaml update works in all cases
-----
[View rendered test/regression/cortx-k8s-tests.md](https://github.com/walterlopatka/cortx-k8s/blob/CORTX-29698_regression_test_update/test/regression/cortx-k8s-tests.md)
> CORTX-29698: Update regtests for v0.2.0 solution.yaml updates

- k8_cortx_cloud/logs-cortx-cloud.sh
- k8_cortx_cloud/status-cortx-cloud.sh
- k8_cortx_cloud/upgrade-cortx-cloud.sh
In a recent change I added support for deploying CORTX into a specified namespace.  However, I neglected to make corresponding changes in the `status-cortx-cloud.sh` and `logs-cortx-cloud.sh` scripts.  This PR addresses those.
(I will be adding regression tests for these over the next few days.)
- This change fixes an issue: CORTX-30780
I tested this by manually running `status-cortx-cloud.sh` and `logs-cortx-cloud.sh` with CORTX deployed in a namespace called `cortx1`. 
> CORTX-30780: Update status and logs scripts with proper namespace

- k8_cortx_cloud/deploy-cortx-cloud.sh
3rd party helm chart releases need to be pinned to specific releases verified to work in the CORTX system.
This change pins helm chart versions by hard-coding them in the deploy-cortx-cloud.sh script.  (This will be
improved on in future refactoring of the CORTX helm charts.)
- This change fixes an issue: CORTX-30971
I have deployed a cortx cluster using this change.
> CORTX-30971: Pin helm chart release versions

- test/regression/deploy.py
- test/regression/destroy.py
- test/regression/test_deploy.py
- test/regression/testrunner.py
This change replaces `#!/usr/bin/python3` with the more appropriate `#!/usr/bin/env python3`.
- This change is related to an issue: CORTX-30015
This change impacts only the regression test scripts.  This change was tested by running those scripts.
> CORTX-30015: Specify python3 bin with "/usr/bin/env python3"

- k8_cortx_cloud/generate-cvg-yaml.sh
- test/regression/cluster.py
This addresses some issues flagged by Codacy.
In cluster.py, the most important and significant changes are in breaking up the complex function generate_solution_file().  I also reduced line lengths on a number of other lines that flake8 was complaining about.
- This change fixes an issue: CORTX-31082
I ran cortx-k8s regression test.
I also ran some manual tests around solution.yaml changes.
> CORTX-31082: Address Codacy Issues

- .github/linters/ct.yaml
- charts/cortx/Chart.lock
- charts/cortx/Chart.yaml
- charts/cortx/README.md
- charts/cortx/README.md.gotmpl
- charts/cortx/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-networkpolicy.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/status-cortx-cloud.sh
Add Consul as a dependency to the new CORTX chart. The CORTX chart is now optionally responsible, via Helm, for installing Consul.
None
- This change fixes an issue: CORTX-30140
N/A
Deployed a new release using this PR. Performed basic I/O.
Tested backwards compatibility by deployed a release prior to this PR. Then ran all of the updated utility scripts against that deployment. The deployment script no longer needs to install it manually.
The deployment script installs a hard-coded release named `cortx`. This changes some of the downstream dependencies as the consul resources are named based on the release (i.e. release `consul` to release `cortx`).
The consul chart is controlled via values in the CORTX values.yaml file. It has been configured to the default values based on the deployment …
> CORTX-30140: Consul managed as cortx Helm Chart dependency

- charts/cortx/Chart.lock
- charts/cortx/Chart.yaml
- charts/cortx/README.md
- charts/cortx/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
- k8_cortx_cloud/status-cortx-cloud.sh
Add Kafka as a dependency to the new CORTX chart. The CORTX chart is now optionally responsible, via Helm, for installing Kafka. Follow up to #230.
- This change fixes an issue: CORTX-30140
Deployed a new release using this PR. Performed basic I/O.
Tested backwards compatibility by deploying a release prior to this PR. Then ran all of the updated utility scripts against that deployment (although, see Additional information).
`solution.common.resource_allocation.kafka.log_persistence_request_size` has been removed from the solution config file. Persistence for the log directory is not enabled, so the value is unused.
The `status-cortx-cloud.sh` script will report a failure for Kafka Cluster IP services when running against an earlier deployment, since the names of the services have …
> CORTX-30140: Kafka managed as cortx Helm Chart dependency

- .github/workflows/lint.yaml
Update GitHub workflows to use recently forked actions.
Addresses [CORTX-31113](https://jts.seagate.com/browse/CORTX-31113).
> CORTX-31113: Use forked actions

- README.md
Mention required `yq` version in the top-level README.
- This change is related to an issue: CORTX-28885
N/A
-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/yq-version/README.md)
> Mention required yq version

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Bump CORTX images to build 803
- N/A
cortx-k8s regression test
> Bump CORTX images to build 803

- k8_cortx_cloud/upgrade-cortx-cloud.sh
Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>
- This change fixes an issue: #
- https://jts.seagate.com/browse/CORTX-30260
- `cortx-data:2.0.0-811
- `cortx-rgw:2.0.0-811
- `cortx-control:2.0.0-811
> Cortx 30260: Added version compatibility check feature to upgrade script

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Upgrade to latest CORTX release.
Deployed and performed S3 I/O and some CSM operations.
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/blob/version-bump/charts/cortx/README.md)
> Bump CORTX version to 817

- README.md
- k8_cortx_cloud/VERSION
- k8_cortx_cloud/logs-cortx-cloud.sh
- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/upgrade-cortx-cloud.sh
v0.8.0 release, which delivers two changesets from the integration branch (via cherry-pick)
Also the latest cortx image version is used (837)
- This change fixes an issue: 
CORTX-32320
CORTX-32063
NA
* Ran cortx-k8s regression tests
* Ran basic S3 IO
-----
[View rendered README.md](https://github.com/Seagate/cortx-k8s/blob/v0.8/README.md)
> v0.8 Merge

- k8_cortx_cloud/VERSION
Bump version in integration branch to v0.9.0.dev
By careful code review.
> Bump version to v0.9.0.dev

- test/regression/cluster.py
- test/regression/deploy.py
- test/regression/make_solution.py
- test/regression/test_deploy.py
- test/regression/testlists/alltests.yaml
- test/regression/testlists/deploy_all.yaml
- test/regression/testlists/deploy_cortx.yaml
- test/regression/testrunner.py
Signed-off-by: Walter Lopatka <wlopatka@gmail.com>
Key changes:
* Change "solution.yaml" builder from custom python code to using yq (plus updating the many dependencies on that)
* Removed test that deploys with solution_stub.yaml
- This change fixes an issue: CORTX-33576
Ran through the automated test framework
> CORTX-33576: Update regression tests to support v0.9.0

- charts/cortx/README.md
- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_images.tpl
- charts/cortx/templates/control/deployment.yaml
- charts/cortx/templates/control/pvc.yaml
- charts/cortx/templates/control/service.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Cleanup Control chart values, in the same vein as previous changes.
- Rename object from `cortxcontrol` to `control`
- Consolidate service definition
- etc.
Deploy, and other scripts. S3 I/O and CSM API requests.
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/blob/CORTX-32157_control-refactor/charts/cortx/README.md)
> CORTX-32157: Refactor Control chart values

- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
`find` complains about the removed `cortx-cloud-helm-pkg` directory. Check if it exists first.
Deploy and destroy cluster.
> Silence some script warnings

- .github/linters/chart_schema.yaml
- .github/linters/ct.yaml
Update chart-testing configuration to validate the Chart schema. Ensure correctness of `Chart.yaml`.
CI lint check.
To run locally requires an installation of yamale.
```
pip install --user yamale
PATH=$HOME/.local/bin:$PATH ct lint --config .github/linters/ct.yaml
```
> Validate Chart schema

- GLOSSARY.md
Glossary terms update for the Kubernetes Operator Functional Specification.
- This change fixes an issue: #CORTX-33142
-----
[View rendered GLOSSARY.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-33142_glossary_update/GLOSSARY.md)
> CORTX-33142 - FS glossary updates

- k8_cortx_cloud/VERSION
Bump VERSION to v0.11.0_dev in integration branch
N/A
> Bump VERSION to v0.11.0_dev

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Bump CORTX version to 920.
S3 I/O, CSM requests.
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/blob/version-bump/charts/cortx/README.md)
> Bump CORTX version to 920

- CONTRIBUTING.md
- GLOSSARY.md
- charts/cortx/templates/_helpers.tpl
- doc/advanced-deployment-scenarios.md
- doc/cortx-aws-k8s-installation.md
- doc/prereq-deploy-use-cases.md
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/logs-cortx-cloud.sh
- test/regression/utils.py
Various spelling fixes and whitespace cleanup.
-----
[View rendered CONTRIBUTING.md](https://github.com/keithpine/cortx-k8s/blob/fix-spelling/CONTRIBUTING.md)
[View rendered GLOSSARY.md](https://github.com/keithpine/cortx-k8s/blob/fix-spelling/GLOSSARY.md)
[View rendered doc/advanced-deployment-scenarios.md](https://github.com/keithpine/cortx-k8s/blob/fix-spelling/doc/advanced-deployment-scenarios.md)
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/keithpine/cortx-k8s/blob/fix-spelling/doc/cortx-aws-k8s-installation.md)
[View rendered doc/prereq-deploy-use-cases.md](https://github.com/keithpine/cortx-k8s/blob/fix-spelling/doc/prereq-deploy-use-cases.md)
> Fix spelling

- GLOSSARY.md
Glossary updates for the Probes Functional Specification to reflect changes in the FS template.
- This change fixes an issue: #CORTX-32834
Spell checked locally.
-----
[View rendered GLOSSARY.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-32834-glossary-updates/GLOSSARY.md)
> CORTX-32834 - glossary updates to reflect template change

- k8_cortx_cloud/VERSION
Bump VERSION to v0.13.0_dev
N/A
N/A
N/A
> Bump VERSION to v0.13.0_dev

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Bump CORTX version to 950
- `cortx-data:950`
- `cortx-rgw:950`
- `cortx-control:950`
Basic sanity test
-----
[View rendered charts/cortx/README.md](https://github.com/walterlopatka/cortx-k8s/blob/bump_version_950/charts/cortx/README.md)
> Bump CORTX version to 950
