- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-cm-nodeconfig.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
Implemented node config strategy as discussed on this morning's call. This is robust enough to extend to other configuration options, yet lean enough to be removed should we determine better environment checking strategies. 
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/Seagate/cortx-k8s/blob/UDX-6765_set_max_map_count/doc/cortx-aws-k8s-installation.md)
> UDX-6765 set max map count

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
Ability for users to select LoadBalancer versus NodePort exposure for external facing services (`cortx-*-loadbal-svc-*`).
> UDX-6831 - Add NodePort vs LoadBalancer flag support

- k8_cortx_cloud/generate-cvg-yaml.sh
This script will be able to generate the necessary YAML block for large node & drive combinations, preventing the need for manually editing the solution.yaml file. 
The default command will output the updated YAML to stdout:
`./generate-cvg-yaml.sh -x test-106-nodes.txt -y test-106-devices.txt -c 2 -d 52 -s "solution9_106.yaml" -e "200Gi" -n "200Gi"`
To update a solution.yaml file, you can redirect output:
`./generate-cvg-yaml.sh -x test-106-nodes.txt -y test-106-devices.txt -c 2 -d 52 -s "solution9_106.yaml" -e "200Gi" -n "200Gi" > new-solution9_106.yaml`
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/Seagate/cortx-k8s/blob/UDX-6528_simplify_solution_yaml_editing/doc/cortx-aws-k8s-installation.md)
> UDX-6528 simplify solution yaml editing

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
Adding new endpoint to list of consul endpoint. This endpoint have protocol http and port pointing to 8500.
This endpoint will be consumed by CSM and S3 for connecting to consul.
> Adding http endpoint in list of consul endpoints

- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- detect 'NotReady' worker nodes at the beginning of the deploy/destroy script and ask the users whether they want to proceed or exit the script early (UDX-6949)
- in deploy script, exit early if InitContainer fails to run (UDX-6921)
> UDX-6949_improve_deploy_destroy_script_robustness

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_dummy.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
This is an initial implementation to allow deployers to specify setup_size in the solution.yaml and have it passed into the running containers to allow for downstream resource management.
This fix will be replaced in the future with business logic that will map setup_size to specific CPU & RAM container resources, to be implemented in Helm Chart logic, that would then specify the explicit limits and requests on each container running in the system. See updated [EOS-27448](https://jts.seagate.com/browse/EOS-27448)
> EOS-27403 - Initial pass at simple setup_size impl

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-pod.yaml
I tested this by deploying (1-node cluster) and running some S3 IO.
> EOS-27400: Remove "sleep infinity" from HA container commands

- .gitignore
- k8_cortx_cloud/logs-cortx-cloud.sh
The `cortx-control` and `cortx-data` pod names changed, so the log collector script has been updated to reflect that.
Added additional pods to collect from, `cortx-ha` and `cortx-server`.
I found an unrelated issue where the CSM agent container logs had an error string that caused a bash `printf` to truncate the logs. 
Another issue that I saw (not addressed in this PR) is that the CORTX support bundle generate is not specifying a container to run on, so k8s is picking the first container. This should be followed up to either select a default container to run the bundle on, or determine whether bundles should be generated for each container individually.
> EOS-27405: Update log collector to use correct pod names

- doc/cortx-aws-k8s-installation.md
- Add instructions where users can also generate their own cortx-all image instead of using the image hosted on ghcr.io
-----
[View rendered doc/cortx-aws-k8s-installation.md](https://github.com/r-wambui/cortx-k8s/blob/rose-cortx-all-image/doc/cortx-aws-k8s-installation.md)
> Include generate cortx-all container image in the documentation

- k8_cortx_cloud/deploy-cortx-cloud.sh
Please review.
I don't love having hard-coded timeouts in the script.  For reference:
- CORTX Control:  timeouts 120s/60s, actual observed time 40-60s
- CORTX Data: timeouts 120s/60s, actual observed time ~80s
- CORTX Server: timeouts 120s/60s, actual observed time ~80s
- CORTX HA: timeouts 30s/30s, actual observed time ~0s
("actual observed time" is on lab VMs in a 5-node cluster)
> EOS-27502: Change from bash loop wait to "kubectl wait" for CORTX pods

- .github/workflows/lint.yaml
- .shellcheckrc
Lint all bash scripts using [shellcheck](https://github.com/koalaman/shellcheck) for any push to main or integration branches and PRs.
Some extra strict options are enabled in .shellcheckrc (v0.8.0 required). All of the enabled checks cover some aspects of several Bash style guides, although they aren't all identical:
- [bahamas10/bash-style-guide](https://github.com/bahamas10/bash-style-guide)
- [BashGuide/Practices](http://mywiki.wooledge.org/BashGuide/Practices)
- [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html)
For now, the Action is configured to always succeed because of existing failures.
> EOS-27541: Add Github Action for shellcheck

- k8_cortx_cloud/logs-cortx-cloud.sh
When `kubectl exec` or `kubectl cp` are used without a container name, a
warning is printed and the first container is used automatically. This
is fine but the warnings might confuse the status of the results so we
prefer to avoid them.
For support bundle generation, any of the pod's containers are a valid
selection, so use the first one listed.
Note that for kubectl v1.21+, the
`kubectl.kubernetes.io/default-container` annotation could be used to
select a default container, thus avoiding any special logic to pick a
container.
> EOS-27546: Silence 'Defaulting container name' log collection messages

- k8_cortx_cloud/deploy-cortx-cloud.sh
The for loop is unnecessary.  The solution.yaml file contains a single block of secrets.
Unless there is a compelling reason to keep this logic, I think it should be simplified.
> EOS-28535: Remove for loop in function deployCortxSecrets()

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
New configuration fields in solution.yaml:
```yaml
solution:
common:
s3:
default_iam_user:
```
Also new corresponding secret: `s3_default_iam_secret_key`
This also changes the "s3" section in config.yaml to "rgw"
> EOS-28022: Support default IAM configuration fields

- k8_cortx_cloud/status-cortx-cloud.sh
When I removed the services cortx-control-headless-svc and cortx-control-clusterip-svc in https://github.com/Seagate/cortx-k8s/pull/70, I did not realize there was a "status-cortx-cloud.sh" that checked for the existence of these services.
This pull request removes those checks from status-cortx-cloud.sh.
> EOS-28544: Remove check from status for control-headless / -clusterip svcs

- k8_cortx_cloud/upgrade-cortx-cloud.sh
Add a utility script to upgrade the container images used in a deployed CORTX cluster. This assumes the solution is the `cortx-all` images which are set uniformally for all containers, e.g. `cortx-all:2.0.0-624-custom-ci`.
Based on #77, this script scales down all the Pods to 0 replicas, updates all of the container images for each of the CORTX Deployments, and scales the Pods back to 1 replica. Scaling up and down are handled by existing scripts. No other upgrade logic is performed besides setting a new image.
We prefer to use Helm to manage all of this and keep a history of changes, but attempts to do so were not successul, so for now this approach is sufficient.
Note that this PR also introduces some improvements to how the solution config file is loaded. In order to discourage the use …
> EOS-27425: Distruptive container image upgrades

- k8_cortx_cloud/logs-cortx-cloud.sh
The `cortx_support_bundle generate` command was recently changed to require the `--cluster_conf_path` argument. Not specifying it results in a cryptic Python error. Previously we relied on the default being selected.
Update the container exec command to specify the argument as newly required.
This is confirmed to work using image `cortx-all:2.0.0-632-PI61.2`.
> CORTX-28699: Update `cortx_support_bundle` command for log collection

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
The ports exposed by external services can now be customized using `solution.yaml`. This includes:
- S3 http and https port
- CORTX Control API port (CSM https)
Configuration of the container ports and application ports (within those containers) is not configurable.
Additional changes:
- The solution file (and Helm charts) allows optional assignment of NodePorts for each of the service ports (applicable to NodePort and LoadBalancer service types). It is now simple to expose nodePorts by default, for test or development purposes, directly from the solution configuration. 
- S3 and CORTX Control service types now default to `NodePort` instead of `LoadBalancer`.
- Removed the default `nodePort` value for the cortx-control service.
- Fixed a bug where `nodePort` was configured for the …
> CORTX-27406: Allow customization of external service ports

- README.md
First, the minikube link was 404. While fixing that I noticed that both links were using absolute paths. Relative are better because they resolve appropriately within a branch. Using an absolute link means you have to choose which branch and embed that in the URL.
Signed-off-by: John Bent <john.bent@seagate.com>
-----
[View rendered README.md](https://github.com/Seagate/cortx-k8s/blob/johnbent-patch-1/README.md)
> Fixing broken links and improving them

- k8_cortx_cloud/status-cortx-cloud.sh
Two Issus are addressed by this PR.
**CORTX-29125: Update status-cortx-cloud.sh to return exit code 1 on failure.**
Previously status-cortx-cloud.sh always returned 0.  This PR brings two changes:
1. On failure this script returns 1
2. At the end of the script it prints a summary.  Either:
a. A note that all status checks passed
b. A count of status checks that failed
**CORTX-29126: Do not check for LoadBalancer service type**
Previously, status-cortx-cloud.sh assumed that the service type
for the cortx-control-loadbal-svc and cortx-server-loadbal-svc
was "LoadBalancer". This is no longer the case. In fact, the default
type is now "NodePort". This is not a useful status check anyway,
so this changset removes the check for the service type.
> CORTX-29125: update status-cortx-cloud.sh to return exit code 1 on failure

- README.md
Update docs to reflect recent changes to `solution.yaml` for external services configuration.
Fix some spelling errors.
-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/CORTX-29121_doc-updates/README.md)
> CORTX-29121: Doc updates for external services changes

- .github/workflows/lint.yaml
- k8_cortx_cloud/logs-cortx-cloud.sh
- This { is literal. Check expression (missing ;/\n?) or quote it. [SC1083]
- Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore). [SC2312]
- Quote to prevent word splitting/globbing, or split robustly with mapfile or read -a. [SC2206]
- In [[..]], use && instead of -a. [SC2108]
- Don't use variables in the printf format string. Use printf '..%s..' "$foo". [SC2059]
- Prefer [[ ]] over [ ] for tests in Bash/Ksh. [SC2292]
- Expanding an array without an index only gives the first element. [SC2128]
- Double quote to prevent globbing and word splitting. [SC2086]
- Prefer putting braces around variable references even when not strictly required. [SC2250]
> CORTX-29144: Fix shellcheck issues in logs-cortx-cloud.sh

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
The `solution.yaml` and platform Helm chart have been updated to support the ability to create multiple CORTX IO Services. This service provides access to the RGW servers for S3 IO. By default, only one service is created. Multiple services can be created for redundancy in a cloud environment.
- Multiple service instances are only supported for the `LoadBalancer` service type. Defining multiple `ClusterIP` or `NodePort` services doesn't provide any benefit, so those are fixed to a single instance.
- If custom nodePorts are configured, the first instance of the service will take the specified nodePort value, and the port number will be incremented for each additional service instance. The port numbers must not conflict else the deployment will fail.
- The service names are assigned based …
> CORTX-28899: Ability to create multiple LoadBalancer IO services

- k8_cortx_cloud/solution.yaml
New images:
* ghcr.io/seagate/cortx-all:2.0.0-664
* ghcr.io/seagate/cortx-rgw:2.0.0-664
> CORTX-28969: Update solution.yaml with latest supported images

- test/regression/checker.py
- test/regression/cluster.py
- test/regression/cortx-k8s-tests.md
- test/regression/deploy.py
- test/regression/destroy.py
- test/regression/example_config.yaml
- test/regression/test_deploy.py
- test/regression/testlists/alltests.yaml
- test/regression/testlists/deploy_all.yaml
- test/regression/testlists/deploy_cortx.yaml
- test/regression/testrunner.py
- test/regression/utils.py
This PR introduces basic regression tests for cortx-k8s.  The goal of these tests is to implement a smoke test for cortx-k8s scripts and template files.  These tests do not introduce comprehensive system tests for CORTX.
This first release has two tests which follow the same pattern.
* TEST-DEPLOY-0001 deploys using cortx images
* TEST-DEPLOY-0002 deploys using stub (centos7) images
Each test follows this sequence:
1. Run "prereq"
2. deploy-cortx-cloud.sh
3. status-cortx-cloud.sh (confirm everything passes)
4. shutdown-cortx-cloud.sh
5. start-cortx-cloud.sh
6. destroy-cortx-cloud.sh
More checks can be added to this sequence, but at least it exercises all scripts (except upgrade).
-----
[View rendered test/cortx-k8s-tests.md](https://github.com/walterlopatka/cortx-k8s/blob/CORTX-28579_basic …
> CORTX-28579:  Basic regression tests for cortx-k8s

- .github/workflows/lint.yaml
- k8_cortx_cloud/status-cortx-cloud.sh
Fix the following shellcheck errors/warnings:
- Don't use variables in the printf format string. Use printf '..%s..' "$foo". [SC2059]
- Double quote to prevent globbing and word splitting. [SC2086]
- Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore). [SC2312]
- Expanding an array without an index only gives the first element. [SC2128]
- Useless echo? Instead of 'echo $(cmd)', just use 'cmd'. [SC2005]
- node_list_str appears unused. Verify use (or export if used externally). [SC2034]
- Prefer [[ ]] over [ ] for tests in Bash/Ksh. [SC2292]
- Prefer putting braces around variable references even when not strictly required. [SC2250]
- $/${} is unnecessary on arithmetic variables. [SC2004]
SC2312 is disabled completely in this script since …
> CORTX-29144: Fix shellcheck issues in status-cortx-cloud.sh

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
- k8_cortx_cloud/deploy-cortx-cloud.sh
Updating according to latest [sample config.yaml](https://github.com/Seagate/cortx-prvsnr/blob/2210210cb493cd7f7a3ee99496bc90e69179f1ea/conf/solution/config.yaml.sample) example.
Fix container command for client pods.
After deploying with this change, the `config.yaml` in the ConfigMap matches the sample file. However, I am unable to test any kind of functionality. As far as I can tell, these settings are ignored by the CORTX components, as I cannot find any processes listening on the configured ports. Regardless, `hctl status` looks normal, and S3 I/O is successful.
> CORTX-27683: Update hax and motr endpoint values

- CODEOWNERS
Removing CODEOWNERS file from the `cortx-test` branch, as those commits and PRs are not managed or need to be overseen by the `cortx-k8s-admin` group (which is only managing `integration` and `main` branch PRs).
Per https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location, the CODEOWNERS file should exist in the base branch we desire code owners to receive requests for. Therefore, it doesn't need to exist in the `cortx-test` branch for the time being.
> removing CODEOWNERS from cortx-test

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
Secrets are only required in init containers, where the secrets are encrypted and stored during provisioning. Regular containers access the secrets via the cluster config file.
> CORTX-28509: Remove secrets mounts from non-init containers

- README.md
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
Cosmetic change only, no functional difference. Since the port value is an integer, `null` makes a little more sense to use than an empty string.
`""`, '~'`, `null` or the omission of the node port values are all valid and have the exact same behavior, which results in the assignment of random port numbers.
-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/CORTX-29234_nodeport-defaults/README.md)
> CORTX-29234: Default nodePorts to `null` in solution.yaml

- test/regression/cluster.py
With commit 42f996b the command-line interface to prereq-deploy-cortx-cloud.sh changes so that instead of positional args it takes -d / -s args.  This update to the regtest file adapts to that change.
> CORTX-27775: Update prereq regtest with interface change

- README.md
This PR removes two references to openldap in README.md.  (These should have been removed as part of #141).
-----
[View rendered README.md](https://github.com/walterlopatka/cortx-k8s/blob/CORTX-29541_remove_openldap_from_readme/README.md)
> CORTX-29541: Remove remaining references to openldap from README.md

- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
We have decided that rather than make such a significant
change as generating passwords by default that we would
first issue a written warning that this will happen in the
next release.
This changeset restores the CORTX passwords that were removed
as part of the prior CORTX-29122 change.  This change
will be reverted in the next release in a few weeks after
the QA and DevOps teams have had a chance to accommodate
these changes.
> CORTX-29122: Restore CORTX passwords

- k8_cortx_cloud/upgrade-cortx-cloud.sh
This PR updates upgrade-cortx-cloud.sh to upgrade using the "cortx-rgw" image for cortx-server deployments.
This does not change the interface. The user still specified only the "cortx-all" image.  This implementation assumes that the cortx-all and cortx-rgw images will always be built together, with the same version number, and same url path.
> CORTX-29548: Support rgw image in upgrade-cortx-cloud.sh

- README.md
- k8_cortx_cloud/solution.example.yaml
This serves a few purposes:
- Less chance of accidental modifications to the source controlled example
- Avoids accidental use of the wrong file (default as `solution.yaml`) when using files with different names
- Makes it obvious that the default file is just an example that should be customized
-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/solution-rename/README.md)
> Rename `solution.yaml` to `solution.example.yaml`.

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-networkpolicy.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Port number 28051 is the S3 Authserver HTTPs port. This is no longer in use with the switch to RGW.
> CORTX-29672: Remove unused s3 server settings

- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/solution.yaml
- k8_cortx_cloud/solution_stub.yaml
Update Consul image as specified in solution.example.yaml to 1.11.4.
ghcr.io/seagate has been previously updated to contain this image.
I have verified that CORTX deploys with this new image.
> CORTX-29634: Update Consul image version to 1.11.4

- .github/PULL_REQUEST_TEMPLATE.md
This change adds a Pull Request template in order to improve and streamline PR submissions.
-----
[View rendered .github/PULL_REQUEST_TEMPLATE.md](https://github.com/keithpine/cortx-k8s/blob/CORTX-29435_pr-template/.github/PULL_REQUEST_TEMPLATE.md)
> CORTX-29435: Add GitHub Pull Request template

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
Fix the issue template contact links. Some missing fields appear to make them not render.
Add new links pointing to the main CORTX project for feature requests, Discussions for cortx-k8s support, and Slack for general CORTX community support.
- This change is related to an issue: CORTX-29435
Using my fork repo.
> CORTX-29435: Fix contact links (issue forms)

- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/solution.yaml
Bump CORTX images to latest published versions.
N/A
Updated to:
- `cortx-all:2.0.0-713`
- `cortx-rgw:2.0.0-713`
Deployment and basic S3 I/O.
> Bump CORTX images to build 713

- .github/workflows/lint.yaml
- k8_cortx_cloud/generate-cvg-yaml.sh
- Fix all shellcheck errors, warnings and notes:
- Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore). [SC2312]
- Prefer [[ ]] over [ ] for tests in Bash/Ksh. [SC2292]
- Prefer putting braces around variable references even when not strictly required. [SC2250]
- Quote to prevent word splitting/globbing, or split robustly with mapfile or read -a. [SC2206]
- Consider using { cmd1; cmd2; } >> file instead of individual redirects. [SC2129]
- Double quote to prevent globbing and word splitting. [SC2086]
- Fix verbose logging redirect to file
- Fix debug message for `DEVICE_PATHS_FILE`
- Re-enable GitHub lint action for the script.
- This change fixes an issue: CORTX-29537
None
Ran script before and after change with identical parameters and …
> CORTX-29537: Fix shellcheck issues in generate-cvg-yaml.sh

- k8_cortx_cloud/deploy-cortx-cloud.sh
Move Helm Chart repository installation and updating to the "pre-req" function.
While analyzing the deploy script, I noticed that the Hashicorp repo was being
installed in the Rancher local provisioner function, which is confusing and out
of place. Similarly, the Bitnami repo install is in the Zookeeper deployment
function, except there are multiple charts dependent on the install. It makes
more logical sense to move these actions to somewhere else, like the pre-req
function.
- This change is related to an issue: CORTX-29961
N/A
New deployment with repos installed, then a re-deployment.
> Relocate Helm repo install to pre-req function

- .github/workflows/lint.yaml
- k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
* Fix all shellcheck errors, warnings and notes:
* Quote to prevent word splitting/globbing, or split robustly with mapfile or read -a. [SC2206]
* Double quote to prevent globbing and word splitting. [SC2086]
* Declare and assign separately to avoid masking return values. [SC2155]
* Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore). [SC2312]
* Quote the right-hand side of == in [[ ]] to prevent glob matching. [SC2053]
* Useless echo? Instead of 'cmd $(echo foo)', just use 'cmd foo'. [SC2116]
* Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?. [SC2181]
* Prefer [[ ]] over [ ] for tests in Bash/Ksh. [SC2292]
* Prefer putting braces around variable references even when not strictly required. [SC2250]
* <X> appears …
> CORTX-29537: Fix shellcheck issues in prereq-deploy-cortx-cloud.sh

- .github/workflows/lint.yaml
- k8_cortx_cloud/parse_scripts/parse_yaml.sh
- k8_cortx_cloud/parse_scripts/subst.sh
- k8_cortx_cloud/parse_scripts/yaml_extract_block.sh
- k8_cortx_cloud/parse_scripts/yaml_insert_block.sh
- k8_cortx_cloud/parse_scripts/yaml_update_block.sh
Fix shellcheck checks for all scripts in the `parse` directory:
- Double quote to prevent globbing and word splitting. [SC2086]
- Prefer putting braces around variable references even when not strictly required. [SC2250]
- This format string has 2 variables, but is passed 1 arguments. [SC2183]
- Useless echo? Instead of 'cmd $(echo foo)', just use 'cmd foo'. [SC2116]
- Quote the right-hand side of == in [[ ]] to prevent glob matching. [SC2053]
- Prefer [[ ]] over [ ] for tests in Bash/Ksh. [SC2292]
- Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore). [SC2312]
- Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?. [SC2181]
- This change fixes an issue: CORTX-30708
- This change is related to: PR #212 
N/A
Ran all …
> CORTX-30708: Fix shellcheck issues in parse scripts

- test/regression/cluster.py
- test/regression/test_deploy.py
- test/regression/testlists/alltests.yaml
- test/regression/testlists/deploy_all.yaml
This change adds a feature to the regression test `test_deploy.py` to specify a namespace.
When namespace is specified it overrides the namespace specified in the cluster config file.
In addition, a new test that specifies "default" namespace is added (to ensure that deployment
into the default namespace works as expected).
- This change is related to an issue: CORTX-30781
I have run this via ./testrunner.py -c <config> -t testlists/deploy_all.py
> CORTX-30781 Add regression test for default vs other namespace

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-local-pvc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-svc.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/values.yaml
This change fully supports deploying cortx-client pods into the namespace specified by solution.yaml.
- This change fixes an issue: CORTX-29043
No new CORTX image version requirements with this change (but as before it does need to be version 725 or later to support other recent changes).
I deployed CORTX with "num_clients  = 1" to confirm that it deploys into the specified namespace.
> CORTX-30943: Support specified namespace for cortx-client pods

- k8_cortx_cloud/upgrade-cortx-cloud.sh
CORTX-30215: Remove hare bug workaround from upgrade-cortx-cloud.sh script
- This change fixes an issue: #
- ghcr.io/seagate/cortx-all:2.0.0-737
- ghcr.io/seagate/cortx-rgw:2.0.0-737
> CORTX-30215: Remove hare bug workaround from upgrade-cortx-cloud.sh script

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-cm-nodeconfig.yaml
- k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
Signed-off-by: Papan Kumar Singh <papan.kumarsingh@seagate.com>
To avoid same core file name when m0d start with the same pid,
add timestamp in core file name.
Currently core file name is core.<pid>,
Change it to core.<timestamp>.<pid>
- This change fixes an issue: #CORTX-31012
- `cortx-all:<version>`
- `cortx-rgw:<version>`
[root@cortx-data-headless-svc-ssc-vm-rhev4-2614 ~]# sysctl -a | grep core
kernel.core_pattern = core.%t
[root@cortx-data-headless-svc-ssc-vm-rhev4-2614 m0d-0x7200000000000001:0x5a]# pwd
/etc/cortx/motr/m0d-0x7200000000000001:0x5a
[root@cortx-data-headless-svc-ssc-vm-rhev4-2614 m0d-0x7200000000000001:0x5a]# ls
core.1651139893.104  db  db-log  stobs
If this change addresses a CORTX Jira …
> CORTX-31012:  Include timestamp in Core dump filename.

- .github/linters/ct.yaml
- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Update the CORTX images in the example solution file to build 744. This is the most-recent announced release (as of 4/28/22, previous announcement being 731).
Although not being used yet, the CORTX Helm Chart's `appVersion` was updated to match this.
- This change is related to an issue: [CORTX-30893](https://jts.seagate.com/browse/CORTX-30893)
- [`cortx-all:744`](https://github.com/Seagate/cortx/pkgs/container/cortx-all/20895717?tag=2.0.0-744)
- [`cortx-rgw:744`](https://github.com/Seagate/cortx/pkgs/container/cortx-rgw/20895773?tag=2.0.0-744)
Deployed locally with a 2-node cluster. Performed simple I/O.
I am unable to deploy with the current image, 735. Upgrading to 744 fixes this. In the 744 changelog for cortx-hare there is listed this …
> Bump CORTX images to build 744

- README.md
- k8_cortx_cloud/deploy-cortx-cloud.sh
There is a "wait" after each of the cortx helm charts are deployed.  This wait is guarded by a timeout. Prior to this change the timeout values were hard-coded.
With this change in environment variable can override the timeout value.  The supported environment variables are:
* CORTX_DEPLOY_CONTROL_TIMEOUT (default 300s)
* CORTX_DEPLOY_DATA_TIMEOUT (default 300s)
* CORTX_DEPLOY_SERVER_TIMEOUT (default 300s)
* CORTX_DEPLOY_HA_TIMEOUT (default 120s)
This value is passed directly to `kubectl wait --timeout=${TIMEOUT}`
This is being added so that CORTX developers can work around the previously hard-coded timeouts as needed.
- This change fixes an issue: CORTX-31239
Tested locally:
* Set short timeouts for `CORTX_DEPLOY_CONTROL_TIMEOUT` and `CORTX_DEPLOY_HA_TIMEOUT` and verified that they took …
> CORTX-31239: Support variable timeout values in deploy-cortx-cloud.sh

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/other/secret-template.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Remove the custom template file used for creating the CORTX secret, and generate the secret directly with `kubectl create`. This reduces the number of template files to manage, in support of merging the cortx-configmap Chart into the "unified" Chart.
- This change is related to an issue: CORTX-30141
Deployed a cluster and performed S3 I/O for each of these:
- custom passwords in solution.yaml
- auto-generated passwords
- an external secret
Examined the created secret and compared it from previous, no unexpected changes seen.
> CORTX-30141: Remove CORTX secrets custom template file

- charts/cortx/README.md
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
- k8_cortx_cloud/status-cortx-cloud.sh
Add Zookeeper as a dependency to the new CORTX chart. In this case, Zookeeper is already a dependency of Kafka, so we let the Kafka chart manage it. Follow up to PRs #230 and #233.
- This change fixes an issue: CORTX-30140
Deployed a new release using this PR. Performed basic I/O.
Tested backwards compatibility by deploying a release prior to this PR. Then ran all of the updated utility scripts against that deployment (although, see Additional information).
The status-cortx-cloud.sh script will report a failure for Zookeeper Cluster IP services when running against an earlier deployment, since the names of the services have changed. I don't consider this a breaking change, since the status script should reflect what is expected based on how it is supposed to be deployed with the current …
> CORTX-30140: Zookeeper managed as cortx Helm Chart dependency

- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-pod.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
This change will inject the Pod's name and the name of the Kubernetes worker node that it is running on as environment variables into all containers in the Pod. This is required for future changes to Provisioner work inside the initContainers but can also be leveraged by additional components running in long-running Pods as well. 
- This change fixes an issue: # CORTX-31408
Tested and verified locally through deployments on two distinct Kubernetes clusters.
> CORTX-31408: Add NODE_NAME and POD_NAME to runtime env vars in each Pod

- k8_cortx_cloud/deploy-cortx-cloud.sh
We patch the Consul service accounts to disable auto-mounting of the Kubernetes service tokens. However, this requires a restart of the controllers, which in turns causes havoc as the consul Pods crash and restart (they eventually settle down).
The proper solution is to submit a PR upstream to allow disabling auto-mounting via Helm value so we can turn this back on. Or, as a last resort we could pull in a local version of the Chart, or use a fork.
Deployed and noticed there were no consul Pod restarts.
We could make this a script option, but I didn't quite see a need to enable it at this time. If that's necessary, let me know and I can add this functionality.
> temporarily disable Consul serviceaccount patching

- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/destroy-cortx-cloud.sh
This fixes a harmless warning message when running the destroy script, about not finding the (since removed) `cortx-cloud-helm-pkg/cortx-control` chart directory.
- This change is related to an issue: #252 
Deploy and destroy cluster.
Instead of hard-coding a list of directories to delete files from, just search the parent directory. This handles future chart merges. I applied the same logic to the deploy script's cleanup function.
> simplify deploy/un-deploy cleanup

- k8_cortx_cloud/cortx-cloud-3rd-party-pkg/templates/local-path-storage-template.yaml
- k8_cortx_cloud/destroy-cortx-cloud.sh
Change the `reclaimPolicy` of the local path StorageClass to `Delete`, from `Retain`. Note that Delete is the [default](https://kubernetes.io/docs/concepts/storage/storage-classes/#reclaim-policy) policy for dynamic provisioner storage class that doesn't specify any policy, and also the [default](https://github.com/rancher/local-path-provisioner/blob/47ea46952b27e8f60863316af24cc886090326c2/deploy/local-path-storage.yaml#L93) for the Local Path Provisioner.
Using a Retain policy means the cluster administrator needs to manually clean-up the backing data for k8s volumes, after a user deletes their PVCs and PVs. In development usage the local node partitions can easily run out of space without active management, causing deployments to fail. In comparison, if the policy is Delete, the …
> CORTX-30684: change retain policy to Delete for local-path storage

- README.md
- charts/cortx/README.md
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_helpers.tpl
- charts/cortx/templates/hax/service.yaml
- charts/cortx/templates/server/service.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.example.yaml
- k8_cortx_cloud/solution_stub.yaml
- k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
The cluster.yaml endpoint must be configured using the correct service name.
This was a regression introduced by #245. The name of the hax service was changed but the related ConfigMap endpoint value was not.
The solution configuration item `common.hax.service_name` has been removed. The name of the service is assigned based on the Helm Release name (`<fullname>-hax`). This should not be breaking in typical usage, but if any user is relying on a custom name, it is no longer set.
- This change fixes an issue: CORTX-32041
- This change is related to an issue: CORTX-30799
Using image version 803. Deployed cluster and examined the ConfigMap and generated cluster.conf file. The hax URL is correct. Issued cURL commands from a container to the service URL and it is successful.
Note that the hax …
> CORTX-32041: configure HAX http endpoint correctly

- k8_cortx_cloud/start-cortx-cloud.sh
Use new selector to get statefulset and pod lists.
> Use selectors for StatefulSet lookups

- README.md
- k8_cortx_cloud/upgrade-cortx-cloud.sh
* Update README.md to explain that specifying any image causes all three CORTX images to be pulled.
* Update -h help for upgrade-cortx-cloud.sh to explain the same
* Update README.md to describe how to update a single deployment or statefulset only.
- This change fixes an issue: CORTX-32320
N/A
* Documentation change only.
* Verified that commands specified in doc changes function as described (kubectl set image)
-----
[View rendered README.md](https://github.com/walterlopatka/cortx-k8s/blob/CORTX-32320_update_upgrade_docs/README.md)
> CORTX-32320: Update docs for upgrade to clarify how images are used

- charts/cortx/README.md
- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_helpers.tpl
- charts/cortx/templates/control/deployment.yaml
- charts/cortx/templates/data/service-headless.yaml
- charts/cortx/templates/data/statefulset.yaml
- charts/cortx/templates/server/statefulset.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/solution.example.yaml
Various Helm Chart improvements.
- Remove generation of Server endpoints from deploy script. This is done in the Helm templates now.
- Update all port definitions:
- Port numbers to match the current [sample file](https://github.com/Seagate/cortx-prvsnr/blob/1c0926ec0171eddf761bdaae13c91a4f336c288b/conf/solution/config.yaml.sample) and [Ports page](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/791216223/CORTX+Security+Ports+needed+by+CORTX+services).
- Use templates to define the numbers in a single location
- Add names to all containerPorts, and use in related services
- Simplify local block storage class naming
- This change fixes an issue: CORTX-30147
Deploy/destroy cluster, run util scripts, S3 I/O, CSM API requests.
If this change requires newer CORTX or third party …
> CORTX-30147: misc Chart-related cleanup

- charts/cortx/templates/control/deployment.yaml
- charts/cortx/templates/control/service.yaml
- charts/cortx/templates/ha/deployment.yaml
- charts/cortx/templates/ha/service-headless.yaml
- charts/cortx/templates/hax/service.yaml
- k8_cortx_cloud/status-cortx-cloud.sh
Add common selector/match labels to resources that are missing them. This ensures those resources are matched to the ones installed by the Helm Chart and the specific Release instance.
Also updated a few checks in the the status script to rely less on a hard-coded chart Release name.
- This change fixes an issue: CORTX-28584
Deployment, status, and other scripts. S3 I/O, CSM API requests.
> CORTX-28584: Add missing common selector labels

- charts/cortx/templates/control/service.yaml
- charts/cortx/templates/hax/service.yaml
- charts/cortx/templates/server/service.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
- k8_cortx_cloud/status-cortx-cloud.sh
As was done with other services, the Control service has now been renamed using the standard convention, which is the name of the component. The previous service is considered deprecated, still exists, but will be removed in the future. The type of the deprecated one is now ClusterIP, and the new service uses the user specified type.
No, but in a future release the deprecated service will be removed. This is not a breaking change either, unless users are referencing the service name somewhere else. Nothing in the default deployment uses the old service name.
- This change fixes an issue: CORTX-30147
Deply/destroy cluster. Run status script, S3 I/O and CSM API requests.
Deleted deprecated services and status script reported success.
Deleted non-deprecated services and status script …
> CORTX-30147: Rename Control service

- k8_cortx_cloud/upgrade-cortx-cloud.sh
After fixing PR #297, I felt that the script was fragile with all the grepping and case statements. Now that all of the CORTX workloads are labeled with common labels, we can use said labels to simplify the querying and setting of images of active workloads.
Also re-ordered some error checking to bail out earlier when possible.
The script now requires certain labels to be set:
- `app.kubernetes.io/name=<release name>`
- `app.kubernetes.io/component=<component>` where component is server, data, etc.
These labels are always applied when installing the Helm chart. So this won't work on previous deployments that are unlabeled. However, the script is already breaking for past releases due to the switch from Deployment to StatefulSet for Data, Server and Client workloads. So this is the best …
> CORTX-30147: Simplify upgrade by using selector labels

- charts/cortx/README.md
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Remove `cortx.common.release.version` from the generated `config.yaml` file. This simplifies the Chart deployment and reduces the amount of configuration required by users.
When the version is omitted, Provisioner sets a default value. It parses the `RELEASE.info` file located in the container image, which happens to also best represent the actual CORTX version. By not specifying the version, we take advantage of this default behavior, and remove the requirement for users to set it. There shouldn't be any reason a user would be required to set the version when the software already knows it.
- Used current image 845 and a custom image
- Deployed and performed S3 I/O.
- Examined the generated config.yaml ConfigMap entry for correctness
- Viewed …
> CORTX-32157: Remove CORTX version field from Chart

- charts/cortx/README.md
- charts/cortx/values.yaml
Kafka depends on Zookeeper being active and ready to receive connections.  If it cannot connect to Zookeeper within a specified timeout then it will terminate, allowing K8s to restart Kafka.  This behavior is fine, but it will look nicer if Kafka can wait longer before terminating so that it does not show any restarts on deploy.
This changeset increases the Zookeeper connect timeout from the default of 6s to 60s, which looks like plenty of time for Zookeeper to start up in a CORTX environment.
- This change fixes an issue: CORTX-31831
NA
This was tested locally with focus on correct deploy of CORTX on K8s.
Negative testing: In order to verify that this has no negative impact on error cases, I did the following:
By script:
1. In a while loop....
1. create new user (csm API)
2. read back …
> CORTX-31831: Add 60s Zookeeper connect timeout to Kafka container

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Upgrade CORTX images to version 853.
Deployment, S3 I/O, CSM requests.
First attempt at using this version, S3 was not working. Second attempt is working, so not sure if it was a fluke or not...
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/blob/bump-version/charts/cortx/README.md)
> Bump CORTX version to 853

- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/control/deployment.yaml
- charts/cortx/templates/ha/deployment.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
For Control and HA Pods, replace the random UUID machine-id/cluster node IDs, and use the Pod hostname instead, the same way as the Server, Data and Client Pods are done. This simplifies deployment by removing some required values, and makes a `helm upgrade` based Chart upgrade safer since it removes the value randomness.
All environment variables and volume mounts are removed. Provisioner uses the Pod hostname instead.
Note that the `cortx.io/machine-id` Pod labels have been preserved. The HA k8s monitor is using this label (although it appears only to consider the Control Pod and not its own Pod).
- Deployment and other scripts
- S3 I/O
- CSM API requests
If this change addresses …
> CORTX-32157: Replace control/ha UUIDs with hostnames

- k8_cortx_cloud/status-cortx-cloud.sh
The name of the PVC for local-path was changed with the introduction of multiple data pods per node.  Two changes need to be made to the status script as it deals with data PVCs:
1. The status-cortx-cloud.sh script needs to be updated to match the new pattern of the PVC name
2. The total count of PVCs + PVs needs to be multiplied by num pods per node
- This change fixes an issue: #CORTX-33589
Tested as part of the regression test run (deploy / run status-cortx-cloud.sh.
Tested with single and dual cvg per node
> CORTX-33589: Update grep for local-path PVCs

- k8_cortx_cloud/start-cortx-cloud.sh
Fix bug in which --namespace is not specified for one of the commands in start-cortx-cloud.sh.
This prevents cortx-data pods from starting correctly.
- This change fixes an issue: CORTX-33590
Using the cortx-k8s regression test (deploy/shutdown/start)
> CORTX-33590: Add --namespace for cortx-data sts in start-cortx-cloud.sh

- k8_cortx_cloud/logs-cortx-cloud.sh
Collect logs from cortx-client containers.
- This change fixes an issue: CORTX-33591
Ran "logs-cortx-cloud.sh" with solution.common.motr.num_client_inst = 2 (so cortx-client pods are deployed), and verified that 1) there are no warnings in log-cortx-cloud.sh stdout/stderr and 2) the client container logs are present in the output support bundle tar file.
> CORTX-33591: Collect logs from cortx-client containers

- charts/cortx/README.md
- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_images.tpl
- charts/cortx/templates/client/service-headless.yaml
- charts/cortx/templates/client/statefulset.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Refactor the Chart values for the (Motr) client component.
- Remove redundant "cortx" prefix
- Use camelcase to match Helm conventions
- Convert image into an object. Tag is undefined and will default to the Chart `AppVersion` value.
- Default to the real CORTX client image, instead of centos.
- Allow `imagePullPolicy` to be configurable
Deployed cluster, with and without Client enabled. Ran m0 client in container.
Ran `helm template` and saw default values, like the image, being correctly configured.
> CORTX-32157: Refactor client Chart values

- charts/cortx/README.md
- charts/cortx/ci/default-values.yaml
- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_helpers.tpl
- charts/cortx/templates/client/statefulset.yaml
- charts/cortx/templates/control/deployment.yaml
- charts/cortx/templates/data/statefulset.yaml
- charts/cortx/templates/ha/deployment.yaml
- charts/cortx/templates/networkpolicy.yaml
- charts/cortx/templates/server/statefulset.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Refactor the values to be more consistent with Helm conventions, reduce duplication, etc. (general cleanup).
- Remove the `configmap` value and relocate/consolidate child values to the top-level, or within their appropriate component sections.
- Default `clusterName` to the release fullname instead of a hard-coded name.
- Hard-code the RGW "auth_secret". This is not configurable as the Secret is created with the exact value. This is consistent with all of the other secrets, and we have never exposed this setting in solution.yaml.
- Set the secret name to an empty default, and flag it as required so the chart install fails if not specified. Existing secret names can also be a Helm template.
- Hard-code the secret's volume name in the Pod specs, there's not much reason to customize it.
- …
> CORTX-32157: Refactor some Chart values

- README.md
- k8_cortx_cloud/solution.example.yaml
This reverts the default number of S3 Server Pods to one per CORTX node, which is the same as v0.8.0. The default of 3-per-node can require to many resources for some VM environments, so this keeps the number of surprises down for those moving from 0.8.0 to 0.9.0.
Deployed cluster.
> Set default S3 server instance count to 1

- charts/cortx/README.md
- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_images.tpl
- charts/cortx/templates/ha/deployment.yaml
- charts/cortx/templates/ha/pvc.yaml
- charts/cortx/templates/ha/rbac.yaml
- charts/cortx/templates/ha/service-headless.yaml
- charts/cortx/templates/ha/serviceaccount.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Cleanup HA chart values, in the same vein as previous changes.
- Rename object from cortxha to ha
- Document values
- Use camel case for variable names
- Use new image format and simplify assignment in deploy script
Deployed cluster, ran scripts, S3 I/O, CSM APIs
Compared the output of `kubectl get deployments,statefulsets,services,cm -o yaml` from before and after this change, it is identical, minus the unique deployment metadata.
Changed default resources values and saw them applied successfully to the Deployment.
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/ …
> CORTX-32157: Refactor HA chart values

- charts/cortx/README.md
- charts/cortx/templates/_cluster.yaml.tpl
- charts/cortx/templates/_config.yaml.tpl
- charts/cortx/templates/_helpers.tpl
- charts/cortx/templates/_images.tpl
- charts/cortx/templates/data/service-headless.yaml
- charts/cortx/templates/data/statefulset.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/templates/cortx-data-blk-data-pv.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Cleanup Data chart values, in the same vein as previous changes.
* Rename object from cortxdata to data
* Use camel case for variable names
* Use new image style
* Etc.
This has significant changes in regards to the storage set definitions. The storage sets are now defined as a top level list, in the exact same format as [solution.yaml](https://github.com/Seagate/cortx-k8s/blob/6f7cf87636f0020e63f9fda4703914a83f437375/k8_cortx_cloud/solution.example.yaml#L163-L216) except for:
- Key names use camel case
- The `nodes` key is removed since it is not being used. Instead, the `data.replicaCount` defines the number of nodes
The logic to construct the CVG groups and determine the number of StatefulSets has been changed to use Helm (Sprig's really) `chunk` function, which groups all the CVG …
> CORTX-32157: Refactor Data chart values

- charts/cortx/templates/NOTES.txt
- k8_cortx_cloud/deploy-cortx-cloud.sh
Move the final message from the Bash deployment script into the Helm Chart NOTES.txt template. The notes are printed at the end of the chart installation, and since it's a template it has the ability to embed Release-specific values, like service names and input parameters, which aren't as easily retrieved in the Bash script. Regardless, this removes some dependency on the Bash script.
You can re-read the notes again after the Chart install from the helm CLI command, e.g. `helm get notes cortx`, so any instructions are not lost upon clearing/closing a terminal session.
- This change fixes an issue: CORTX-29540
Ran normal deployment. Here's what the new output looks like:
```text
######################################################
###################################################### …
```
> CORTX-29540: Move deploy final message to Chart

- charts/cortx/README.md
- charts/cortx/values.yaml
- k8_cortx_cloud/solution.example.yaml
The default resource settings are too low for a typical VM deployment. Increasing these by a small amount noticeably decreases deployment times. The default values have been chosen based on recommendations from CORTX-27366
I timed deployments using the before and after values, and got the following results. These are not scientific (only ran once for each configuration), but the difference is obvious. Runs typically vary +/- 20 seconds from my observations.
- K8s cluster with 5 worker nodes
- 2 data Pods per CORTX node (2 CVGs w/group size 1)
- 1 server Pod per CORTX node
- 1 client Pod per CORTX node
| CORTX node count | Previous time (seconds) | Current time (seconds) |
|:---:|---|---|
| 2 | 326 | 180 |
| 3 | 367 | 208 |
| 5 | 1118 | 334 |
- This change fixes an issue: CORTX-32355
- …
> CORTX-32355: Increase Consul default resources

- README.md
- k8_cortx_cloud/deploy-cortx-cloud.sh
Specify a custom values.yaml file when using the deployment script to add or override calculated values. This makes it possible to configure things not supported by `solution.yaml`, for example, enabling the Consul Web UI by default.
```bash
❯ cat myvalues.yaml 
consul:
ui:
enabled: true
```
Deploy with the above values file, and I can see the Consul UI is enabled.
Specify a non-existent file, and see an error is report and the deploy script exits before installing.
Specify a blank env var, or none at all, and notice a normal, unmodified deployment (no Consul UI).
-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/deploy-custom-values/README.md)
> Deploy with custom Chart values

- charts/cortx/templates/data/statefulset.yaml
The Data IOS port is starting at the wrong value (off-by-one). This was a regression added in #302, identified in CORTX-29838. 
Now the first IOS instance in the Pod matches the port configure in config.yaml. The containerPort definitions don't affect any functionality in this case, they just serve as documentation.
- This change is related to an issue: CORTX-29838
Deployed, checked StatefulSet definition.
Note that the port numbers configured are not reflected in the runtime state of the CORTX cluster. This is a regression in CORTX software, being tracked by CORTX-33705.
> CORTX-29838: Fix containerPort off-by-one regression

- charts/cortx/templates/control/deployment.yaml
- k8_cortx_cloud/status-cortx-cloud.sh
This change replaces the local PVC with an EmptyDir for the data volume for the cortx-control pod.  The goal of this change is to avoid having the cortx-control pod bound to a specific node.
- This change fixes an issue: CORTX-32842
N/A
1. Verified via local deploy and user creation/S3 IO smoke test.
2. Verified that status-, logs-cortx-cloud.sh scripts
3. Ran basic deploy regression test
> CORTX-32842: Replace PVC with EmptyDir for cortx-control deployment

- charts/cortx/README.md
- charts/cortx/templates/control/deployment.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/start-cortx-cloud.sh
- k8_cortx_cloud/status-cortx-cloud.sh
- test/regression/test_deploy.py
This change provides support for multiple cortx-control pods in a cluster. 
This is supported in helm value: `control.replicaCount`.
There is no support in solution.yaml for this at this time.
- This change fixes an issue: CORTX-33842
N/A
1. Deploy with 1 pod, 3 pods, 10 pods
2. Verify that all cortx-control pods are serving data
3. Verify that all cortx-control pods are in sync (all accept write requests, all return same GET responses)
4. Run basic k8s deploy regression test.
There may be issues with running multiple cortx-control pods in terms of the implementation of those containers.  I have done basic functional test, but I leave it to the team responsible for cortx-control implementation to do due diligence in developer test.
If this change requires newer CORTX or third party image …
> CORTX-33842: Support multiple cortx-control pods

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Update to latest CORTX image release. This includes a number of new changes such as log device support, and partial support Consul Confstore.
- This change fixes an issue: #
- This change is related to an issue: CORTX-33054, 
Deploy a cluster, S3 I/O, CSM APIs.
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/blob/version-bump/charts/cortx/README.md)
> Bump CORTX version to 879

- .gitignore
- README.md
- doc/prereq-deploy-use-cases.md
- k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
This PR implements a fix for the observed "connection reset by peer" issue resulting in underlying Linux networking configuration issues. It is meant as a reference example for how to manage this issue in a Kubernetes environment. 
- This change fixes an issue: #CORTX-33749
- This change is related to an issue: #CORTX-33217
Locally and on test machines. 
-----
[View rendered README.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-33749_add_conntrack_to_prereq_script/README.md)
[View rendered doc/prereq-deploy-use-cases.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-33749_add_conntrack_to_prereq_script/doc/prereq-deploy-use- …
> CORTX-33749 - Workaround for conntrack table issues

- README.md
- charts/cortx/README.md
- charts/cortx/templates/_helpers.tpl
- charts/cortx/templates/_images.tpl
- charts/cortx/templates/client/statefulset.yaml
- charts/cortx/templates/control/deployment.yaml
- charts/cortx/templates/ha/deployment.yaml
- charts/cortx/templates/server/statefulset.yaml
- charts/cortx/values.yaml
- k8_cortx_cloud/deploy-cortx-cloud.sh
Add the ability to control more verbose container logging for cortx-setup InitContainers. When configured, setup log files will be
re-directed to the container's stdout. This allows setup logs to be captured by cluster logging solutions, and aids in troubleshooting, since logs will be available outside of the containers. The alternative is to exec into a debug container and examine the logs manually.
Configure is performed via global and component `setupLoggingDetail` values. Valid settings are:
-  `"default"` (or `""`): no detailed logging
- `"component"`: component-only logging
- `"all"`: component plus all other setup files (e.g. Consul-related)
If the global value is set, it can be overridden by the component version (this the opposite of global image settings).
By default, the …
> CORTX-33135: cortx-setup logging enhancements

- README.md
Due to bug CORTX-29365 Metadata disk size cannot exceed 20TB.
This bug was introduced after migration to Rocky Linux 8.4 and was not present in Centos 7.9.
There are no limitations on data disk size.
Signed-off-by: Jugal Patil <jugal.patil@seagate.com>
> Added Documentation for Metadata disk size limitation.

- charts/cortx/Chart.yaml
- charts/cortx/README.md
- k8_cortx_cloud/solution.example.yaml
Upgrade to CORTX images 886.
Deploy, S3 I/O, CSM API requests.
FYI, I notice a significant performance degradation in S3 I/O, likely due to new debug output going to stderr.
-----
[View rendered charts/cortx/README.md](https://github.com/keithpine/cortx-k8s/blob/bump-version/charts/cortx/README.md)
> Bump CORTX version to 886

- GLOSSARY.md
Glossary updates to reflect Operator SDK / OLM terminology used in the Operator FS.
- This change fixes an issue: #CORTX-33283
- `cortx-data:<version>`
- `cortx-rgw:<version>`
- `cortx-control:<version>`
n/a
-----
[View rendered GLOSSARY.md](https://github.com/Seagate/cortx-k8s/blob/CORTX-33283_operator_fs_glossary_updates/GLOSSARY.md)
> CORTX-33283 - glossary updates for Operator FS

- k8_cortx_cloud/logs-cortx-cloud.sh
Improved error handling in logs-cotrx-cloud.sh:
- On kubectl failures, exit function early (and avoid additional, unhelpful error messages)
- Avoid "kubectl cp" with leading slash (/) on target, which causes an annoying "tar" error.
- This change fixes an issue: CORTX-33534
N/A
Local test:
- Verify no regression
- Test with pods evacuated from one node to see response to kubectl errors
> CORTX-33534: Improve logs-cortx-cloud.sh error handling.

- k8_cortx_cloud/deploy-cortx-cloud.sh
Error check added to deploy-cortx-cloud.sh so that it immediately exits if cortx is already deployed.
- This change fixes an issue: CORTX-31017
N/A
- Verify standard deploy continues to work
- Test on existing cortx deployment in default namespace
- Test on existing cortx deployment in non-default namespace
> CORTX-31017: Add check for cortx already deployed

- k8_cortx_cloud/get-logs-from-pvc.sh
Add a -d option to allow user to specify a subdirectory of the PVC to collect logs from.
- This change fixes an issue: CORTX-34141
Manual test:
- Verified that data for the specified subdirectory only is collected
- Verified that an invalid path will result in an error.  
> CORTX-34141: Add -d option to get-logs-from-pvc.sh

- k8_cortx_cloud/status-cortx-cloud.sh
- test/regression/data-only.yaml
- test/regression/test_deploy.py
- test/regression/testlists/alltests.yaml
- test/regression/testlists/deploy_all.yaml
With v0.10.0 and the introduction of potentially multiple replicas of cortx-control pods, I introduced a regression in status-cortx-cloud.sh, such that the script reported failures with a data-only deployment. This is because logic was added to account for potentially multiple replicas did not take into account a possible data-only deployment.
Along with the fix I have added a basic regression test that deploys with data-only deployment.
- This change fixes an issue: CORTX-34189
N/A
Added new regression test that deploys with data-only deployment.
I also ran the existing regression test to confirm that standard deployment works as expected.
- [ x All commits are signed off and are in agreement with the [CORTX Community DCO and CLA …
> CORTX-34189 Fix status-cortx-cloud.sh regression (data-only deploy)

- charts/cortx/README.md
- charts/cortx/README.md.gotmpl
- k8_cortx_cloud/deploy-cortx-cloud.sh
Helm can update and install Chart dependencies by using the install `--dependency-update` flag. It isn't necessary to manually install the repositories and then build the dependencies.
If the local chart files exist already on the next deployment, Helm won't go out and attempt to update them. So this is a slight optimization in that it's less likely to require contacting the remote Chart repos every deployment.
In the future, we can avoid this completely by creating a CORTX Chart artifact (e.g. `helm package`) and bundle the dependencies with it, and update instructions to use the released Chart (then later, create a Helm repo).
1. Fresh install with no Helm repos installed and a clean "charts" directory. Deploy script adds repos and downloads the charts automatically
2. A subsequent …
> Let Helm manage dependent Chart install

- k8_cortx_cloud/status-cortx-cloud.sh
status-cortx-cloud.sh was checking the total count of consul pods against the sum of expected server pods (max(3, #worker-nodes)) and expected client pods.  However, the expected number is based on the number of worker nodes not tainted w/ NoSchedule.  This does not work as expected when a node that is normally a worker node is tainted with NoSchedule.
To fix I have stopped checking for the expected number of cortx-consul-client pods, and only count cortx-consul-server pods.  This is not a useful check anyway.
- This change fixes an issue: CORTX-34284
NA
Manual test:  deploy cluster, taint one node, run status check... confirm that all pass
Also test with node not tainted to ensure that normal case passes, too.
If this …
> CORTX-34284: Do not count cortx-consul-client pods in status check
